### ISSUE TITLE
Lag in Scrolling testimonial section

### ISSUE THREAD

**Issue by mr-robot01212** [FahimFBA/RainyRoof_Restaurant_Website#16]
Hello there!
The testimonial section seems to be a bit laggy. I don't know the exact reason. But its supper annoying .
Please fix this issue.
Otherwise great website.

**Comment by FahimFBA** [comment]
Thanks a lot for creating an issue to notify me about that problem.  😊
Can you tell me in which device you have found the lagging issue? It would be better for me if I would get to know whether the lag is appearing in the mobile devices or others ([responsiveness](https://en.wikipedia.org/wiki/Responsive_web_design#:~:text=Responsive%20web%20design%20(RWD)%20is,minimum%20to%20maximum%20display%20size.&text=Responsive%20layouts%20automatically%20adjust%20and,tablet%2C%20or%20a%20mobile%20phone.) issue or not). 😀
